"""Initial migration with named constraints

Revision ID: 22ef6fc90510
Revises: 
Create Date: 2025-03-10 07:54:17.942827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ef6fc90510'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogue_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_catalogue', 'catalogue', ['catalogue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_catalogue', type_='foreignkey')
        batch_op.drop_column('catalogue_id')

    # ### end Alembic commands ###
